dist: trusty
sudo: required

notifications:
  email: true

services:
  - docker

language: c

before_install:
  - git clone https://github.com/sancus-pma/sancus-main.git
  - cd sancus-main/docker && make build SANCUS_SECURITY=$SECURITY 

script:
  - docker run --name sancus-ci-run -d -t sancus-devel
  - >
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; 
    then 
    docker exec sancus-ci-run /bin/sh -c 
    "cd /sancus/sancus-examples &&
    ln -s /sancus/sancus-examples /travis_sancus-example &&
    git checkout $TRAVIS_BRANCH"; 
    else 
    docker exec sancus-ci-run /bin/sh -c	
    "git clone https://github.com/${TRAVIS_PULL_REQUEST_SLUG} /sancus-examples-pr &&
    cd /sancus-examples-pr && ln -s /sancus-examples-pr /travis_sancus-example &&
    git checkout $TRAVIS_PULL_REQUEST_SHA";
    fi
  - docker exec sancus-ci-run /bin/sh -c "cd /travis_sancus-example && make SANCUS_SECURITY=$SECURITY ARCHIVE_MODE=$ARCHIVE_MODE $TARGET.sim"
  - docker ps -a

env:
  - TARGET=hello-world   SECURITY=64
  - TARGET=hello-world   SECURITY=128
  - TARGET=hello-library SECURITY=64
  - TARGET=hello-library SECURITY=64 ARCHIVE_MODE=thin
  - TARGET=sensor-reader SECURITY=64
  - TARGET=arithmetic    SECURITY=64
  - TARGET=fileio        SECURITY=64
  - TARGET=timer         SECURITY=64
  - TARGET=violation     SECURITY=64
  - TARGET=sancus-step   SECURITY=64
