dist: trusty
sudo: required

notifications:
  email: true

services:
  - docker

language: c

before_install:
  - git clone https://github.com/sancus-pma/sancus-main.git
  - cd sancus-main/docker && make build SANCUS_SECURITY=$SECURITY 

script:
  - docker run -t sancus-devel /bin/sh -c \
        "cd /sancus/sancus-examples && git checkout $TRAVIS_BRANCH &&
         make SANCUS_SECURITY=$SECURITY $TARGET.sim"
  - docker ps -a

env:
  - TARGET=hello-world   SECURITY=64
  - TARGET=hello-world   SECURITY=128
  - TARGET=sensor-reader SECURITY=64
  - TARGET=arithmetic    SECURITY=64
  - TARGET=fileio        SECURITY=64
  - TARGET=timer         SECURITY=64
  - TARGET=violation     SECURITY=64
  - TARGET=sancus-step   SECURITY=64
